version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: swiftcrew-db
    environment:
      POSTGRES_DB: swiftcrew
      POSTGRES_USER: swiftcrew
      POSTGRES_PASSWORD: swiftcrew123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U swiftcrew"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
